// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"database/sql"
)

type Petroleira struct {
	ID            string
	Organizacao   string
	Nome          string
	Descricao     sql.NullString
	Tags          string
	Qtdrecursos   sql.NullInt32
	Qtdreusos     sql.NullInt32
	Qtddownloads  sql.NullInt32
	Qtdseguidores sql.NullInt32
}
